package com.example.demo.service;

import com.example.demo.model.User;
import com.example.demo.repository.UserRepository;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Nested;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.InjectMocks;
import org.mockito.Mock;
import org.mockito.junit.jupiter.MockitoExtension;

import java.util.Arrays;
import java.util.Collections;
import java.util.List;
import java.util.Optional;

import static org.junit.jupiter.api.Assertions.*;
import static org.mockito.ArgumentMatchers.any;
import static org.mockito.ArgumentMatchers.eq;
import static org.mockito.Mockito.*;

@ExtendWith(MockitoExtension.class)
class UserServiceTest {

    @Mock
    private UserRepository userRepository;

    @InjectMocks
    private UserService userService;

    @Nested
    @DisplayName("getAllUsers")
    class GetAllUsersTests {

        @Test
        @DisplayName("should return all users from repository")
        void shouldReturnAllUsers() {
            List<User> expectedUsers = Arrays.asList(
                    new User(1L, "John Doe", "john.doe@example.com"),
                    new User(2L, "Jane Smith", "jane.smith@example.com"),
                    new User(3L, "Bob Johnson", "bob.johnson@example.com")
            );
            when(userRepository.findAll()).thenReturn(expectedUsers);

            List<User> result = userService.getAllUsers();

            assertEquals(3, result.size());
            assertEquals("John Doe", result.get(0).getName());
            assertEquals("Jane Smith", result.get(1).getName());
            assertEquals("Bob Johnson", result.get(2).getName());
            verify(userRepository, times(1)).findAll();
        }

        @Test
        @DisplayName("should return empty list when no users exist")
        void shouldReturnEmptyList() {
            when(userRepository.findAll()).thenReturn(Collections.emptyList());

            List<User> result = userService.getAllUsers();

            assertTrue(result.isEmpty());
            verify(userRepository, times(1)).findAll();
        }
    }

    @Nested
    @DisplayName("getUserById")
    class GetUserByIdTests {

        @Test
        @DisplayName("should return user when found")
        void shouldReturnUserWhenFound() {
            User expectedUser = new User(1L, "John Doe", "john.doe@example.com");
            when(userRepository.findById(1L)).thenReturn(Optional.of(expectedUser));

            User result = userService.getUserById(1L);

            assertNotNull(result);
            assertEquals(1L, result.getId());
            assertEquals("John Doe", result.getName());
            assertEquals("john.doe@example.com", result.getEmail());
            verify(userRepository, times(1)).findById(1L);
        }

        @Test
        @DisplayName("should return null when user not found")
        void shouldReturnNullWhenNotFound() {
            when(userRepository.findById(99L)).thenReturn(Optional.empty());

            User result = userService.getUserById(99L);

            assertNull(result);
            verify(userRepository, times(1)).findById(99L);
        }
    }

    @Nested
    @DisplayName("createUser")
    class CreateUserTests {

        @Test
        @DisplayName("should create user with auto-generated id")
        void shouldCreateUserWithAutoGeneratedId() {
            List<User> existingUsers = Arrays.asList(
                    new User(1L, "John Doe", "john.doe@example.com"),
                    new User(2L, "Jane Smith", "jane.smith@example.com"),
                    new User(3L, "Bob Johnson", "bob.johnson@example.com")
            );
            User inputUser = new User(null, "New User", "new@example.com");
            User savedUser = new User(4L, "New User", "new@example.com");

            when(userRepository.findAll()).thenReturn(existingUsers);
            when(userRepository.save(any(User.class))).thenReturn(savedUser);

            User result = userService.createUser(inputUser);

            assertNotNull(result);
            assertEquals(4L, result.getId());
            assertEquals("New User", result.getName());
            assertEquals("new@example.com", result.getEmail());
            verify(userRepository, times(1)).findAll();
            verify(userRepository, times(1)).save(any(User.class));
        }

        @Test
        @DisplayName("should assign id 1 when no users exist")
        void shouldAssignId1WhenNoUsersExist() {
            User inputUser = new User(null, "First User", "first@example.com");
            User savedUser = new User(1L, "First User", "first@example.com");

            when(userRepository.findAll()).thenReturn(Collections.emptyList());
            when(userRepository.save(any(User.class))).thenReturn(savedUser);

            User result = userService.createUser(inputUser);

            assertNotNull(result);
            assertEquals(1L, result.getId());
            verify(userRepository, times(1)).save(any(User.class));
        }
    }

    @Nested
    @DisplayName("deleteUser")
    class DeleteUserTests {

        @Test
        @DisplayName("should return true when user is deleted successfully")
        void shouldReturnTrueWhenDeleted() {
            when(userRepository.deleteById(1L)).thenReturn(true);

            boolean result = userService.deleteUser(1L);

            assertTrue(result);
            verify(userRepository, times(1)).deleteById(1L);
        }

        @Test
        @DisplayName("should return false when user not found for deletion")
        void shouldReturnFalseWhenNotFound() {
            when(userRepository.deleteById(99L)).thenReturn(false);

            boolean result = userService.deleteUser(99L);

            assertFalse(result);
            verify(userRepository, times(1)).deleteById(99L);
        }
    }

    @Nested
    @DisplayName("patchUser")
    class PatchUserTests {

        @Test
        @DisplayName("should return updated user when found")
        void shouldReturnUpdatedUserWhenFound() {
            User patchData = new User(null, "Updated Name", null);
            User updatedUser = new User(1L, "Updated Name", "john.doe@example.com");
            when(userRepository.update(eq(1L), any(User.class))).thenReturn(Optional.of(updatedUser));

            User result = userService.patchUser(1L, patchData);

            assertNotNull(result);
            assertEquals(1L, result.getId());
            assertEquals("Updated Name", result.getName());
            assertEquals("john.doe@example.com", result.getEmail());
            verify(userRepository, times(1)).update(eq(1L), any(User.class));
        }

        @Test
        @DisplayName("should return null when user not found for patch")
        void shouldReturnNullWhenNotFound() {
            User patchData = new User(null, "Updated Name", null);
            when(userRepository.update(eq(99L), any(User.class))).thenReturn(Optional.empty());

            User result = userService.patchUser(99L, patchData);

            assertNull(result);
            verify(userRepository, times(1)).update(eq(99L), any(User.class));
        }
    }
}
